services:
  nginx: # 服务名称，用户自定义
    image: nginx:latest  # 镜像版本
    ports:
      - 80:80  # 暴露端口
    volumes: # 挂载
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/files:/usr/share/nginx/files  # 共享文件目录
    privileged: true # 这个必须要，解决nginx的文件调用的权限问题
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment: # 指定用户root的密码
      - MYSQL_ROOT_PASSWORD=123456
  springboot:
    image: springboot:latest
    build: . # 表示以当前目录下的Dockerfile开始构建镜像
    ports:
      - 9090:9090
    volumes:
      - /root/nginx/files:/upload/files  # 映射到应用配置的新路径
    depends_on: # 依赖与mysql、redis，其实可以不填，默认已经表示可以
      - mysql

# 定义持久化卷，确保容器间共享数据
volumes:
  files-volume:  # 用于存储上传的文件