server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xm_film_ticket?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    time-zone: Asia/Shanghai

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}

alipay:
  appId: 9021000144645160
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCYgNDZENrUJRrpBx8LxnpJX8EsZ5DtmtVIk4rxele/OEBoAeRK+PE0HCUQUKrHeoTLN7jmet/0ZPHkWq6nuyYeNzd29XskEG20HGK89ipmRGihzTiy/FG8yGT8WNhF1JgZmROQE/YRdcrKlDpksiN/sL8dddzBluc8PPw/00zCYq/M7jKaj0oHCfWztWmPwYu9zCLHP6/1hjBuUA6H4U2MVWmAfruCVDzX4R5JBw/mbBuSWgl+dq85LOkCLoNCjWkT/Mzy5YF9Esfe4YNU8DN2jNrM8NA8oyxT9+7jcZRYah90Pot3BJc5lPAcAjFb/tg7n69FQvK6D2u2ln4cyxQfAgMBAAECggEASBb8ot+40fgIVIetQV+9htng8yCx/d/nWruEPspamGX67C+Yv2gWfU+gpam8UTe1dmsM2MbU/y6Iui2zyk5JopbvfShl4ZJyiWWxtymWuWk1HOdqGhH0gY0pT7Cf68Knc9JM0RregzpvdnvDbr5W0ZG3hjGk/U5cWLlrdLBp5KkOROoTSmzol8Bz9oLJl4V3bcAe5YtDBIuS75lK/IELBBYJb+GenTXP6bFl0LonUxj1K/X29KhkTWjW0nvQJf3aURvC+buMU6j5iMmf7QuWMBc6VLnnUQD9/3f7WikOgkggcCP2K0HTb+nn/U6q2JCPfvZhmPWmJNo40LNFbplFgQKBgQDZ9AXQ64GygdkTLniCb4B6Y9Yd8rvkD+Z6YAWQ2s9pjoFRBjBFJWov9R5J/fNpQod6m0rSaI4RFQ+mpBu6AK26LTb2Se2po7zSdBAHpqzYQ8yj+ljUjMjJ5t5xVDvDZclyglXOQNenAJxndHPczPP3f4o/Q7VZmdtqUkptvk5N7wKBgQCzH+/iD02w3e5iJh65XFp2K9rgZC5QtTZGRoNjSNFwqIItHtJsuJF9kc1PsqJG1zCd4i08ne326HnoEhgvaTla40j2HVysMRUQiij4VjZfXZwRCvK3ArdBu3x+5ZvhUJPDHyf8DY1/qSTCoxJgy4CdPkQrsJP8Ijdla7vEdm3M0QKBgAVJrFJzRERGbjPO7tGLTvypK2qyluhjkl3psnjfNiUDdhO3KLikvbzIH6H/7UXifVL2LYyJSNkVP7n1RU7v8UcRDcJP7NouxMf+VN06p/rfOjnIOxt9BuoPFdp+Bq0o7QhALUDBxfmhRComYyE6P7kDeSErzVyNJQuhT3j2IwQ1AoGAOodG9JCXjCEYEU3vYBXDITW3MPbLA2gSsee8aqaSeMM2tdOKYif0shkAAviVeZw6sHwE1/eql7DilGfFK0iwivgVEQYLD+CBx4O9W1egMIz/v7naEN58TqgaR8RyqK6ReYImqH8tKvdzoX1zNdmIzthXogbyc8IiY6tOESW5PuECgYAcgjR7WF+7kpRVpkE9lsh588J+gpooS3WVPcuDeycZ565OxqFwKGB8xxEmWfaMiYsEbM0ke9aStcV4ywWWktEaTQkcxv5gl89+cg1WJx+ES3joBOKyZESgeHUxaD3Q3VsvlnZQz8SIHd/is3dF6U1Be5pDJ3YOiJQcwNV9J6WJPQ==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujw81tiedUBlZbpYsTbz9XqrOYYNOn1Ezsb4H29TuD6xvKgMW7EJp/rwfMhlUSsNmhNOcav/geGFzckA1bolOzog+k8E8McYcPsXfxNB9c33lk7EvaOJdxx8argrFhkXa51WP0VNmzdW0+lPHDRVZ8nMO6LnypHafis7RMJcjV9jXS2yjlpJ8yHzsYGCLTpnlNjszYbV2hQ3qcPmRh8ctWFMxEsNAigTfZIhjari9IRU60rCdASkO5VeMvC5NfdDT0bIbwSHhnJa68kdjUN5RaHkkLVknsU8ZkJpGgxrED57kAqgH3qHPumGSEyqxe39AuNKc15Nxn9761HLRStbpQIDAQAB
  notifyUrl: http://mfz4ym.natappfree.cc/alipay/notify


