server:
  port: 9090

# 文件上传配置
file:
  upload-dir: ${user.dir}/files/  # 开发环境下保存在项目目录
# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xm_film_ticket?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  jackson:
    time-zone: Asia/Shanghai

# 配置mybatis实体和xml映射
mybatis:
  configuration:
    # 开发环境可以保留SQL日志，但通过logback控制输出级别
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

fileBaseUrl: http://localhost:${server.port}

alipay:
  appId: 9021000144645160
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCUoRzjm62jRyWcKosvg8liRM0lAslQSGK4hduN0wAAh9xSLmKDos/9UoOU5L+GomADn+Fy1sEh/XMrAakCC4cSPnIvtQYSybpyXp5/1pt+h2OQp2bQhyq0b+kJ7LNYYSiaJyAlj6vaNkM9G1I3tw56q9AW0lvK8juCI8xqcO8SALfkUET18oC24mee5i3wK8MxPHTLOv0EpX25+Wn84k1zfdWHjifPBzxOUZ5DdYW8P/EbxxEuAh6nQLMEeXekBElQ7u+9eTuoQSJkcDEZuwwyCNay+oIPfMRzWpZ+brHgjcEMZ8HqztEyJfZVZEYd9da12r/VHImBOCoPbbQIoTWpAgMBAAECggEAUJozBYhGmTabQd6cjs8EZoNzUS/6pswqpXEKSRZ1eNQ0+mhnSoYAD5ww+Y04BLaIJU8OP24RXPKLA3aqBg7kWFN/LzoXqha2QxHnGOL0fqDDsQ3npwy2bxYFpjk0ZaiDEV5Ig7Yvd25X9oqbgtWGR6ZnegjoeN32wbPSRqMqM3NQPpIVQsgu3GRA106DhH8mookHABmpMRiOeWEqsj4YS5i2UtfC4QQhUEArHRhIyBvsoXSXRdNMPZlGWxWyIVvXduKMSMvfhiyve1YwmhtL38w5IxCzmi2wB74lFbSmtMYbS8yOfxsRNVuwfYfm1XB7EYWAedzhZPN6mKdCn5fCAQKBgQD5miXjffvjQMxpqzVx7iQDfvE6aoOB1HtQE3nJVHZC5BTNyYDnBR4Wg52SxxjnNmr7Twr7g4enR0DHUogitbgTYQdvRppZBiKJJwKggEX2ZFUkhows/4AHDxoO4SyXWgEhb6vPaGHMjxrG6doJLYrAUaa7yfeX2eY0F2IYR+mvaQKBgQCYcGV9ReDHP6cDtdJaEcG2rj20SWrpaM+A5TPqtV4DY2ZzwPm+ByofgDqBw3WQXbw0m1IlR2eor+fON9D7VT4QvGGreH18FaVnfTDb3GUlKq8hOf7MCM+gUUGypyoHRN/JyUOMQkPfYysujAPoWjo0YJVMgKhpCy7I7Y07DeTMQQKBgQDpJDnlv0SrZVhKD1iRfY34EfeCyADkITO5fSeRjaoVGvPvsBsOLrKG9xMVCZFSTnspGBC7E4V/E0gHpihwu2of9864+qqrItbZYy3J+2beGaOJxX9jfJf6f/moEl3TVYee0q8ZwXcwWi75w28ciYSD1QC3gZQaK7chywGeinVVmQKBgDI1gxgZ9glqq8YLEzfbdWSIS4agT/iFLyOTWuBJ0KdpDAvAWgH/Nh6eC6dGC+j7Fsx1BD+HH1tuZPmFZO4Di6fThJAH5b0DHDHUCE3CcAYn4vscsRHfLRPu76a6bJtsUhGSmw8NnHFtpoF0WK0lWtp5nXNPRSkkJ8rCg6wZzWyBAoGBAJfi48XRHioFMMwILALhIsZ4QtVOzi4hMwKzyNFiihjy/bNHOAoQeehw28GY540SFsRo6KytUDd1ionYZ0yzlZudP47oP+tm+F3cAUHWQvHPaCeSU7YheZKYE6y0yf+AsPyjuJrtYPhh+uqOFkNYR6RLbvVfVY+K7cezx0EewXeb
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujw81tiedUBlZbpYsTbz9XqrOYYNOn1Ezsb4H29TuD6xvKgMW7EJp/rwfMhlUSsNmhNOcav/geGFzckA1bolOzog+k8E8McYcPsXfxNB9c33lk7EvaOJdxx8argrFhkXa51WP0VNmzdW0+lPHDRVZ8nMO6LnypHafis7RMJcjV9jXS2yjlpJ8yHzsYGCLTpnlNjszYbV2hQ3qcPmRh8ctWFMxEsNAigTfZIhjari9IRU60rCdASkO5VeMvC5NfdDT0bIbwSHhnJa68kdjUN5RaHkkLVknsU8ZkJpGgxrED57kAqgH3qHPumGSEyqxe39AuNKc15Nxn9761HLRStbpQIDAQAB
  notifyUrl:  http://2jspyn.natappfree.cc /alipay/notify


